# GitHub Auto-Labeler Configuration (v5)

documentation:
  - changed-files:
    - any-glob-to-any-file: ['**/*.md', 'docs/**/*']

server:
  - changed-files:
    - any-glob-to-any-file:
      - 'server/**/*'
      - '!server/src/modules/auth/**/*' # Let auth label handle this
      - '!server/**/*.test.js'

client:
  - changed-files:
    - any-glob-to-any-file:
      - 'client/**/*'
      - '!client/src/components/**/*' # Let ui label handle this
      - '!client/src/app/**/*' # Let ui label handle this

testing:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.test.{js,jsx,ts,tsx}'
      - '**/__tests__/**/*'
      - 'server/e2e/**/*'

auth:
  - changed-files:
    - any-glob-to-any-file:
      - 'server/src/modules/auth/**/*'
      - 'server/src/middlewares/auth.middleware.js'
      - 'client/src/app/(auth)/**/*'

ui:
  - changed-files:
    - any-glob-to-any-file:
      - 'client/src/components/**/*'
      - 'client/src/app/**/*'
      - '!client/src/app/api/**/*'

styling:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.css'
      - '**/tailwind.config.js'

configuration:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'docker-compose.yml'
      - 'Dockerfile'
      - '.env.example'
      - '.github/**/*'

ci-cd:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'
      - 'Dockerfile'
